export const symbolCategories = [
  { id: "audio-sources", label: "Audio sources" },
  { id: "cv-sources", label: "CV sources" },
  { id: "audio-modifiers", label: "Audio modifiers" },
  { id: "cv-modifiers", label: "CV modifiers" },
  { id: "custom", label: "Custom" }
];

export const symbols = [
  { id: "sine-wave-oscillator", label: "Sine wave oscillator", category: "audio-sources", frame: "circle", glyphs: ["sine"] },
  { id: "triangle-wave-oscillator", label: "Triangle wave oscillator", category: "audio-sources", frame: "circle", glyphs: ["triangleWave"] },
  { id: "sawtooth-wave-oscillator", label: "Sawtooth wave oscillator", category: "audio-sources", frame: "circle", glyphs: ["saw"] },
  { id: "square-wave-oscillator", label: "Square wave oscillator", category: "audio-sources", frame: "circle", glyphs: ["squareWave"] },
  { id: "oscillator-pwm", label: "Oscillator with PWM", category: "audio-sources", frame: "circle", glyphs: ["pwm"] },
  { id: "noise", label: "Noise", category: "audio-sources", frame: "circle", glyphs: ["noise"] },
  { id: "wavetable-oscillator", label: "Wavetable oscillator", category: "audio-sources", frame: "circle", glyphs: ["wavetable"] },
  { id: "granular-synthesis", label: "Granular synthesis", category: "audio-sources", frame: "circle", glyphs: ["grains"] },
  { id: "microphone-input", label: "Microphone input", category: "audio-sources", frame: "circle", glyphs: ["mic"] },
  { id: "sample-player", label: "Sample player", category: "audio-sources", frame: "circle", glyphs: ["play"] },
  { id: "sample-recorder", label: "Sample recorder", category: "audio-sources", frame: "circle", glyphs: ["record"] },
  { id: "physical-modelling-generic", label: "Physical modelling", category: "audio-sources", frame: "circle", glyphs: ["cube"] },
  { id: "pipe-physical-modelling", label: "Pipe physical modelling", category: "audio-sources", frame: "circle", glyphs: ["pipe"] },
  { id: "string-physical-modelling", label: "String physical modelling", category: "audio-sources", frame: "circle", glyphs: ["string"] },
  { id: "membrane-physical-modelling", label: "Membrane physical modelling", category: "audio-sources", frame: "circle", glyphs: ["membrane"] },
  { id: "speech-synthesis", label: "Speech synthesis", category: "audio-sources", frame: "circle", glyphs: ["speech"] },

  { id: "keyboard-controller", label: "Keyboard controller", category: "cv-sources", frame: "square", glyphs: ["keyboard"] },
  { id: "touch-controller", label: "Touch controller", category: "cv-sources", frame: "square", glyphs: ["touch"] },
  { id: "cv-gate-sequencer", label: "CV+Gate sequencer", category: "cv-sources", frame: "square", glyphs: ["knobs"] },
  { id: "trigger-sequencer", label: "Trigger sequencer", category: "cv-sources", frame: "square", glyphs: ["steps"] },
  { id: "source-clock", label: "Source clock", category: "cv-sources", frame: "square", glyphs: ["fourDots", "bpmText"] },
  { id: "cv-recorder", label: "CV recorder", category: "cv-sources", frame: "square", glyphs: ["recorderPanel"] },
  { id: "lfo-sine", label: "LFO sine", category: "cv-sources", frame: "square", glyphs: ["sine"] },
  { id: "lfo-triangle", label: "LFO triangle", category: "cv-sources", frame: "square", glyphs: ["triangleWave"] },
  { id: "lfo-square", label: "LFO square wave", category: "cv-sources", frame: "square", glyphs: ["squareWave"] },
  { id: "lfo-reset-sync", label: "LFO with reset sync", category: "cv-sources", frame: "square", glyphs: ["lfoReset"] },
  { id: "tempo-synced-lfo-triangle", label: "Tempo synced LFO triangle", category: "cv-sources", frame: "square", glyphs: ["triangleWave", "bpmText"] },
  { id: "tempo-synced-lfo-saw", label: "Tempo synced LFO saw", category: "cv-sources", frame: "square", glyphs: ["rampDown", "bpmText"] },
  { id: "eg-ad", label: "EG AD", category: "cv-sources", frame: "square", glyphs: ["ad"] },
  { id: "eg-ar", label: "EG AR", category: "cv-sources", frame: "square", glyphs: ["ar"] },
  { id: "eg-adsr", label: "EG ADSR", category: "cv-sources", frame: "square", glyphs: ["adsr"] },
  { id: "eg-dadsr", label: "EG DADSR", category: "cv-sources", frame: "square", glyphs: ["dadsr"] },
  { id: "eg-ahdsr", label: "EG AHDSR", category: "cv-sources", frame: "square", glyphs: ["ahdsr"] },
  { id: "looping-eg-ahdsr", label: "Looping EG AHDSR", category: "cv-sources", frame: "square", glyphs: ["ahdsr", "loopArrow"] },
  { id: "looping-eg-dadsr", label: "Looping EG DADSR", category: "cv-sources", frame: "square", glyphs: ["dadsr", "loopArrow"] },
  { id: "looping-eg-adsr", label: "Looping EG ADSR", category: "cv-sources", frame: "square", glyphs: ["adsr", "loopArrow"] },
  { id: "looping-eg-ar", label: "Looping EG AR", category: "cv-sources", frame: "square", glyphs: ["ar", "loopArrow"] },
  { id: "looping-eg-ad", label: "Looping EG AD", category: "cv-sources", frame: "square", glyphs: ["ad", "loopArrow"] },
  { id: "bias-voltage", label: "Bias voltage", category: "cv-sources", frame: "square", glyphs: ["plusV"] },
  { id: "voltage-slider", label: "Voltage slider", category: "cv-sources", frame: "square", glyphs: ["plusMinusVSlider"] },
  { id: "stepped-random-cv", label: "Stepped random CV", category: "cv-sources", frame: "square", glyphs: ["steppedRandom"] },
  { id: "smooth-random-cv", label: "Smooth random CV", category: "cv-sources", frame: "square", glyphs: ["smoothRandom"] },
  { id: "envelope-follower", label: "Envelope follower", category: "cv-sources", frame: "square", glyphs: ["envelopeFollower"] },

  { id: "low-pass-filter", label: "Low-pass filter", category: "audio-modifiers", frame: "triangle", glyphs: ["lowpass"] },
  { id: "low-pass-filter-resonant", label: "Low-pass filter resonant", category: "audio-modifiers", frame: "triangle", glyphs: ["lowpassRes"] },
  { id: "high-pass-filter", label: "High-pass filter", category: "audio-modifiers", frame: "triangle", glyphs: ["highpass"] },
  { id: "high-pass-filter-resonant", label: "High-pass filter resonant", category: "audio-modifiers", frame: "triangle", glyphs: ["highpassRes"] },
  { id: "band-pass-filter", label: "Band-pass filter", category: "audio-modifiers", frame: "triangle", glyphs: ["bandpass"] },
  { id: "notch-filter", label: "Notch filter", category: "audio-modifiers", frame: "triangle", glyphs: ["notch"] },
  { id: "amplifier-vca", label: "Amplifier VCA", category: "audio-modifiers", frame: "triangle", glyphs: ["arrowUp"] },
  { id: "low-pass-gate-lpg", label: "Low-pass gate", category: "audio-modifiers", frame: "triangle", glyphs: ["lpg"] },
  { id: "ring-modulator", label: "Ring modulator", category: "audio-modifiers", frame: "triangle", glyphs: ["ringmod"] },
  { id: "mixer-audio", label: "Mixer", category: "audio-modifiers", frame: "triangle", glyphs: ["mixer"] },
  { id: "attenuator-audio", label: "Attenuator", category: "audio-modifiers", frame: "triangle", glyphs: ["attenuator"] },
  { id: "crossfader", label: "Crossfader", category: "audio-modifiers", frame: "triangle", glyphs: ["crossfader"] },
  { id: "inverter-audio", label: "Inverter", category: "audio-modifiers", frame: "triangle", glyphs: ["inverter"] },
  { id: "waveshaper", label: "Waveshaper", category: "audio-modifiers", frame: "triangle", glyphs: ["waveshaper"] },
  { id: "wave-folder", label: "Wave folder", category: "audio-modifiers", frame: "triangle", glyphs: ["wavefolder"] },
  { id: "half-wave-rectifier-audio", label: "Half wave rectifier", category: "audio-modifiers", frame: "triangle", glyphs: ["halfRect"] },
  { id: "clipper-saturation", label: "Clipper saturation", category: "audio-modifiers", frame: "triangle", glyphs: ["clipper"] },
  { id: "full-wave-rectifier-audio", label: "Full wave rectifier", category: "audio-modifiers", frame: "triangle", glyphs: ["fullRect"] },
  { id: "reverb", label: "Reverb", category: "audio-modifiers", frame: "triangle", glyphs: ["reverb"] },
  { id: "delay", label: "Delay", category: "audio-modifiers", frame: "triangle", glyphs: ["delay"] },
  { id: "chorus", label: "Chorus", category: "audio-modifiers", frame: "triangle", glyphs: ["chorus"] },
  { id: "phase-shifter", label: "Phase shifter", category: "audio-modifiers", frame: "triangle", glyphs: ["phase"] },
  { id: "comb-filter", label: "Comb filter", category: "audio-modifiers", frame: "triangle", glyphs: ["comb"] },
  { id: "switch-audio", label: "Switch", category: "audio-modifiers", frame: "triangle", glyphs: ["switcher"] },

  { id: "attenuator-cv", label: "Attenuator", category: "cv-modifiers", frame: "diamond", glyphs: ["attenuator"] },
  { id: "attenuverter", label: "Attenuverter", category: "cv-modifiers", frame: "diamond", glyphs: ["attenuverter"] },
  { id: "mixer-cv", label: "Mixer", category: "cv-modifiers", frame: "diamond", glyphs: ["cvMixer"] },
  { id: "utility-mixer", label: "Utility mixer", category: "cv-modifiers", frame: "diamond", glyphs: ["mixer", "plusMinusV"] },
  { id: "attenuverting-mixer", label: "Attenuverting mixer", category: "cv-modifiers", frame: "diamond", glyphs: ["mixer", "attenuator"] },
  { id: "matrix-mixer", label: "Matrix mixer", category: "cv-modifiers", frame: "diamond", glyphs: ["matrix"] },
  { id: "dc-coupled-vca", label: "DC coupled VCA", category: "cv-modifiers", frame: "diamond", glyphs: ["dcVca"] },
  { id: "precision-adder", label: "Precision adder", category: "cv-modifiers", frame: "diamond", glyphs: ["precisionAdder"] },
  { id: "buffered-multiple", label: "Buffered multiple", category: "cv-modifiers", frame: "diamond", glyphs: ["bufferedMultiple"] },
  { id: "switch-cv", label: "Switch", category: "cv-modifiers", frame: "diamond", glyphs: ["switcher"] },
  { id: "clock-divider", label: "Clock divider", category: "cv-modifiers", frame: "diamond", glyphs: ["noteDivide"] },
  { id: "clock-multiplier", label: "Clock multiplier", category: "cv-modifiers", frame: "diamond", glyphs: ["noteMultiply"] },
  { id: "inverter-cv", label: "Inverter", category: "cv-modifiers", frame: "diamond", glyphs: ["inverter"] },
  { id: "half-wave-rectifier-cv", label: "Half wave rectifier", category: "cv-modifiers", frame: "diamond", glyphs: ["halfRect"] },
  { id: "full-wave-rectifier-cv", label: "Full wave rectifier", category: "cv-modifiers", frame: "diamond", glyphs: ["fullRect"] },
  { id: "comparator", label: "Comparator", category: "cv-modifiers", frame: "diamond", glyphs: ["comparator"] },
  { id: "sample-and-hold", label: "Sample and hold", category: "cv-modifiers", frame: "diamond", glyphs: ["sampleHold"] },
  { id: "quantizer", label: "Quantizer", category: "cv-modifiers", frame: "diamond", glyphs: ["quantizer"] },
  { id: "slew-limiter", label: "Slew limiter", category: "cv-modifiers", frame: "diamond", glyphs: ["slew"] },
  { id: "gate-delay", label: "Gate delay", category: "cv-modifiers", frame: "diamond", glyphs: ["gateDelay"] },
  { id: "logic-and-function", label: "Logic AND function", category: "cv-modifiers", frame: "diamond", glyphs: ["logicAnd"] },
  { id: "logic-nand-function", label: "Logic NAND function", category: "cv-modifiers", frame: "diamond", glyphs: ["logicNand"] },
  { id: "logic-or-function", label: "Logic OR function", category: "cv-modifiers", frame: "diamond", glyphs: ["logicOr"] },
  { id: "logic-xor-function", label: "Logic XOR function", category: "cv-modifiers", frame: "diamond", glyphs: ["logicXor"] },

  { id: "custom-module", label: "Custom module", category: "custom", frame: "custom", glyphs: [] }
];

export const symbolMap = Object.fromEntries(symbols.map((symbol) => [symbol.id, symbol]));

export function getSymbolAssetPath(symbolId, basePath = "") {
  return `${basePath}/symbols/${symbolId}.svg`;
}
